### ISSUE TITLE
Doesn't load "New Features" in some languages

### ISSUE THREAD

**Issue by golbin** [adobe/brackets.io#106]
I'm Korean and it doesn't work in Korean locale.

The problem is the checking logic whether there is a version info resource in the specific locale or not. And the problem of the logic is about async.

![brackets io](https://cloud.githubusercontent.com/assets/6277035/4246590/3fbaf3d6-3a4d-11e4-808f-3e1968e0c488.png)

**Comment by marcelgerber** [comment]
@Jin-Kim Should work again.
