### ISSUE TITLE
Update Screenshot

### ISSUE THREAD

**Issue by marcelgerber** [adobe/brackets.io#117]
We should update the screenshot as it's outdated now.
Maybe use something like https://github.com/adobe/brackets/wiki/Brackets-Screenshots (but without the shadow!)

**Comment by peterflynn** [comment]
Those screenshots include a bunch of stuff that's not actually in the Brackets core download... I think it would be better to have screenshots that reflect the actual "stock" appearance.

**Comment by mynetx** [comment]
@MarcelGerber Is this issue still current?

**Comment by marcelgerber** [comment]
You're right, this has been addressed in the website update for 1.0
Closing.
