### ISSUE TITLE
Dialog and button to open dialog have different titles

### ISSUE THREAD

**Issue by Mark-Simulacrum** [adobe/brackets.io#124]
The `Installation Requirements` button opens a dialog called `Requirements`. Perhaps this should be changed for a cleaner user experience.

**Comment by mynetx** [comment]
@Mark-Simulacrum Where do you find the `Installation Requirements` button?  Could you provide a screenshot?

**Comment by marcelgerber** [comment]
The button is no longer present.
Closing.

@jublo Thanks for reminding us to close this, even if indirectly :)
