### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by nicolo-ribaudo** [adobe/brackets.io#129]
I'm going to translate brackets.io into Italian, but I have two questions:
1. What should I write in the `_last.translated` property? `e1598a31476b10bbfdd1c83614307b2e92bb949d`?
2. Isn't there a way to translate the _Popular Extensions_ section (the title and the _Check Out New Extensions_ button)? I can't find it in the `translation.json` file...

**Comment by marcelgerber** [comment]
Nice, you're welcome!
1. Yep, that's correct (taking the SHA of the last change, like we do in Brackets core, isn't as easy here).
2. No, it's not yet translatable, but we may add it anytime.

**Comment by TomMalbran** [comment]
For 2, we should use the i18n information from the package. Since the text is hardcoded, I guess that we would need a script to generate that.

**Comment by nicolo-ribaudo** [comment]
We can read titles and descriptions from the `package-i18n` property of the _package.json_ files.

Translated: #130
