### ISSUE TITLE
Clicking Download bundled build button on IE 11 navigates to github page, instead of downloading .msi

### ISSUE THREAD

**Issue by bchintx** [adobe/brackets.io#133]
1. using IE 11 (on Win8.1), browse to http://brackets.io
2. click the big, blue `Download Brackets 1.1 + Extract (Preview) by Adobe` button

Observed:
IE 11 navigates to https://github.com/adobe/brackets/releases/tag/release-1.1

Expected:
that the browser would offer to download the .msi

**Comment by pthiess** [comment]
@bchintx I wasn't able to reproduce.

**Comment by bchintx** [comment]
@pthiess Please try reproducing using the native IE 11 application launched from the Desktop.  Upon further investigation, it appears that the problem doesn't reproduce using the (Metro UI) IE 11 app launched from the Start Page.

**Comment by pthiess** [comment]
@bchintx You are right, there seems to be a glitch – I can see the github URL appearing in the URL bar but browser doesn’t go there in my case.

**Comment by mynetx** [comment]
@bchintx @pthiess Cannot reproduce this on IE 11.11.10586 with neither the big blue button nor the small ‘without Extract’ link. Suggesting to close this issue.

**Comment by bchintx** [comment]
thanks for pointing that out @jublo.  Agreed.  The problem appears fixed w/ IE 11.11.10586, running on Windows 10 with the latest "Threshold 2" update.

I'm still seeing the problem on IE 11.0.10240.16590, running on the original, shipping Windows 10, though.  However, it definitely appears to be a problem specific with IE, and not with our website, so I'm fine with closing this issue.
