### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by fmoliveira** [adobe/brackets.io#151]
Hello,

I love Brackets and I'd like to translate its website to my native tongue, Brazilian Portuguese.

I've already read locale's README and I'm opening an issue just to make sure nobody else is working at the same task.

May I start working on the translation? :smiley: 

Thanks in advance!

**Comment by nethip** [comment]
@fmoliveira I think we already have these translations in the core. https://github.com/adobe/brackets/tree/master/src/nls/pt-br. Are you referring to the same strings?

**Comment by nethip** [comment]
@fmoliveira Oh I see now that you were referring to adding new language to the website. My bad as I thought it was to do with Brackets core.

**Comment by nethip** [comment]
Marking this to @ryanstewart for his inputs on this.

**Comment by fmoliveira** [comment]
Hi @nethip , yes I mean adding the new translation to the website. No problem! :smiley: 

I'll await for @ryanstewart answer. Thanks!

**Comment by marcelgerber** [comment]
@fmoliveira I think you're pretty safe with that as there hasn't been much interest in translating this page lately.

In case you need help, I'm probably the one to ask as I've integrated the i18next library and provided the German translation.
There are presumably some small changes we have to make to the localization system over here (the one that comes to mind is accepting locales consisting of two parts, like `pt-br` does).

**Comment by fmoliveira** [comment]
Fine @MarcelGerber , that's exactly what I thought.

Good to know who to ask help for. I'll start working on the translation then. :+1: 

Thanks!

**Comment by nethip** [comment]
@fmoliveira I think this page cannot be completely localized as updates strings that fill the bottom left part of the website telling about release highlights,  are right now localized only in 5 languages and we do not have update strings for  pt-br. I will have a word with Ryan, who is the product manager for Brackets.

**Comment by fmoliveira** [comment]
I see @nethip , you mean the "release notes" section?

If I can help translating the release notes I'll be happy to help too. :smiley:

**Comment by ryanstewart** [comment]
@fmoliveira I think translating the page in the same way @MarcelGerber did for German would be awesome! As @nethip mentions, the release notes won't necessarily be translated (and I don't think we have the infrastructure set up for those) but translating the blog would be awesome.

**Comment by nethip** [comment]
@fmoliveira I just had a word with Ryan. Please go ahead and add the translation. :smile:

**Comment by nethip** [comment]
@ryanstewart that was quick man.

**Comment by marcelgerber** [comment]
@fmoliveira You can translate Brackets' Update Notifications [over here](https://github.com/adobe/brackets-updates/tree/master/updates/stable), but let's start with the website.

**Comment by fmoliveira** [comment]
Thanks a lot @ryanstewart , @nethip and @MarcelGerber .

Fine @MarcelGerber , good to know. You're right, let's start with the website. :+1:

**Comment by fmoliveira** [comment]
So sorry it's taking too much time to finish this. In fact I've already finished the translation but wasn't able to manage time to review it. I'll take care of it this week and submit a pull request.

**Comment by fmoliveira** [comment]
Phew! I've finally been able to do my last review and submit the translation!

PR #161 has been sent. :smiley:

**Comment by abose** [comment]
@fmoliveira The pr has been merged. Please close this issue once you verfied this after release 1.4 goes live.

**Comment by fmoliveira** [comment]
Fine @abose , I'll keep an eye on that!

Thanks.

**Comment by fmoliveira** [comment]
Release 1.4 isn't out yet but the website has already been updated.

Everything is just fine. I'm closing this.
