### ISSUE TITLE
No libgcrypt-11 package

### ISSUE THREAD

**Issue by ghost** [adobe/brackets.io#159]
Debian 8 has no libgcrypt-11 package(only the development package), from where can I get it?

**Comment by marcelgerber** [comment]
Please head over to https://github.com/adobe/brackets/issues/10255 for this discussion. Looks like http://ftp.acc.umu.se/mirror/cdimage/snapshot/Debian/pool/main/libg/libgcrypt11/ is the place to download the libgcrypt11 package.

Notice this repo (brackets.io) is just for the Brackets website, not Brackets itself.

Closing.
