### ISSUE TITLE
Menu icon in mobile web browsers is incorrect.

### ISSUE THREAD

**Issue by ericjim** [adobe/brackets.io#19]
In both Chrome for Android and Firefox for Android; the icon at the top right corner that drops down the navigation menu presents an erroneous icon.
##### Firefox for Android (Version: 24.0)

![brackets mobile site firefox](https://f.cloud.github.com/assets/1329167/1319318/b5ae3b36-32db-11e3-9b9d-761fea891de2.png)
##### Chrome for Android (Version: 30.0.1599.82)

![brackets mobile site chrome](https://f.cloud.github.com/assets/1329167/1319316/a1c88676-32db-11e3-9859-4eb77e67203d.png)

**Comment by larz0** [comment]
Thanks @ericjimenez. It should be fixed now.
