### ISSUE TITLE
Download Button Not Recognizing Firefox 32-bit

### ISSUE THREAD

**Issue by adrocknaphobia** [adobe/brackets.io#26]
The download button displays "unknown" when browsing the site with Firefox 32-bit.

https://github.com/adobe/brackets/issues/5509

**Comment by lkcampbell** [comment]
@adrocknaphobia, I have this problem in Chrome as well.  Version 30.0.1599.101 m.

The download button says "Sprint 32 (UNKNOWN)" if I go to http://brackets.io/ and if I click on the button, is goes to an error page that says:

struct
DETAIL   [empty string]
MESSAGE  Invalid platform.

On the other hand, the Download Button at http://download.brackets.io/ works great!  That's the page and button I have been using to get all of my latest Sprint downloads.

**Comment by peterflynn** [comment]
@lkcampbell What's your user agent?

**Comment by lkcampbell** [comment]
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36

**Comment by pthiess** [comment]
@adrocknaphobia Are you still on this or shall we reassign?

**Comment by peterflynn** [comment]
Reviewed.  Will reassign to @ingorichter once he's been added to the repo.

**Comment by peterflynn** [comment]
Note: we should also make sure this is fixed for various browsers on 32-bit Win XP (see adobe/brackets#5914)

**Comment by adrocknaphobia** [comment]
Should be working for all XP browsers now.

**Comment by TuckerWhitehouse** [comment]
`If(OS != "Unknown")` is NEVER going to return false ([Line 287](https://github.com/adobe/brackets.io/blob/gh-pages/index.html#L287)) because the default value given on [Line 259](https://github.com/adobe/brackets.io/blob/gh-pages/index.html#L259) is `var OS = "UNKNOWN"` (all caps).

**Comment by pthiess** [comment]
@adrocknaphobia I do agree with @TuckerWhitehouse in case of an unknown OS version and label are set to an undefined value. It would be great to handle that case. Your fix seems to address XP, but not necessarily unsupported platforms.

**Comment by adrocknaphobia** [comment]
Thanks @TuckerWhitehouse. Good catch. I fixed the issue w/ PR #34. In the future, feel free to submit pull requests directly against this repo. It's my hope that we can handle these minor cosmetic issues without having to bother the Brackets team whose time is better spent working on Brackets itself.
