### ISSUE TITLE
Does not working on OS X Mavericks

### ISSUE THREAD

**Issue by scarnago** [adobe/brackets.io#27]
Brackets Sprint 32" can't open because coming form a not identify developer

**Comment by ericjim** [comment]
Try locating Brackets in the Applications folder, and perform a Right-click open. This will allow you to open third-party applications that are not distributed via the Apple Mac App Store, or that are not identified officially with Apple. If you go to System Preferences ---> Security & Privacy, under "Allow apps downloaded from:" you can change your settings to "Anywhere". This should allow you open any apps always, regardless of where they came from, however, Apple would probably advise that you leave it at "Mac App Store and Identified developers". Right-click opening an app enables you to individually open 3rd party apps that are not from the app store, or from identified developers, on a one-by-one basis.

**Comment by ZweiSteinSoft** [comment]
@scarnago @ericjimenez This repository is for the Brackets website only. For the software, refer to [adobe/brackets issues](/adobe/brackets/issues).

**Comment by larz0** [comment]
Thanks @mynetx @ericjimenez. Closing.
