### ISSUE TITLE
Shows "Sprint 31" while loading

### ISSUE THREAD

**Issue by njx** [adobe/brackets.io#28]
While brackets.io is loading, it shows "Sprint 31" and an old set of features on the home page, then switches to the current sprint. We should just blank these out until the latest info is loaded.

(I noticed this first because the first time I hit brackets.io it was slow, but even when it loads fast you can still see it switch from Sprint 31 to the current sprint.)

**Comment by couzteau** [comment]
On my VM Chrome and IE never switch to 33

**Comment by adrocknaphobia** [comment]
Dropped sprint indicator on button before update check.
