### ISSUE TITLE
No Sprint 29 download for Win/Mac

### ISSUE THREAD

**Issue by marcelgerber** [adobe/brackets.io#31]
There's no entry in `All downloads` for Win/Mac for Sprint 29.
The file extension `deb` for Linux is missing, too.

![image](https://f.cloud.github.com/assets/2641501/1483211/79420cfa-46f3-11e3-95bf-342024e4366a.png)

**Comment by adrocknaphobia** [comment]
Uploaded and tested new builds for Sprint 29.
