### ISSUE TITLE
Make the list of blog posts dynamic

### ISSUE THREAD

**Issue by ingorichter** [adobe/brackets.io#40]
Currently the list with blog posts is static and requires a manual update, if there is a new blog post on blog.brackets.io.

**Comment by GarthDB** [comment]
It wouldn't be hard to bring in the feed http://blog.brackets.io/feed/ 
It is probably best to do server side, but this is all gh-pages, so a quick js solution would work.

**Comment by larz0** [comment]
It's now dynamic, closing.
