### ISSUE TITLE
Blog RSS Feed broken

### ISSUE THREAD

**Issue by screendriver** [adobe/brackets.io#42]
I wanted to subscribe to the Brackets Blog RSS Feed (http://blog.brackets.io/feed/). Unfortunately I got a "Error establishing a database connection"

See also [ adobe/brackets#6620](https://github.com/adobe/brackets/issues/6620)

**Comment by pthiess** [comment]
Hey Bryan,

please take a look at this - marking it a medium for now. @jadbox @ingorichter @bchintx 

I consider this a high priority if more people are seeing this.

**Comment by marcelgerber** [comment]
Seems to work fine now. It wasn't working here a few hours ago either (same machine, same browser, ...).

**Comment by screendriver** [comment]
:+1:

**Comment by ingorichter** [comment]
@SAPlayer @ScreenDriver We had to restart the database server. Since we dynamically update the blogposts on brackets.io, the blog instance gets more hits, which most likely caused this issue. We are looking to resolve this situation. Thanks for reporting.

**Comment by marcelgerber** [comment]
~~Seems like http://blog.brackets.io is completely down now :thumbsdown: 
http://isup.me/blog.brackets.io~~

EDIT: Was just for a short moment, it's up again. Hope this won't happen more often.

**Comment by jadbox** [comment]
We could move to the blog wordpress instance to another hosting platform that specializes in scalable solutions (e.g. Wordpress.org || wpengine.com). This should allow us to put the crashing issue at rest, since a good provider should dynamically expand the WP instances. Any blockers/concerns around moving blog servers? Either I or someone on the team can perform the transition.

**Comment by bchintx** [comment]
The feed is up, and we're working on migrating to a new WordPress hosting service.

**Comment by bchintx** [comment]
The blog has been moved to our new hosting service, and the JSON feed has been re-established.  Closing this bug.

@ScreenDriver please comment if you are experiencing any problems with it now.
