### ISSUE TITLE
We're getting blog posts from the distant future.

### ISSUE THREAD

**Issue by larz0** [adobe/brackets.io#44]
![screen shot 2014-02-19 at 9 04 12 am](https://f.cloud.github.com/assets/1495261/2209144/1f852930-9988-11e3-9153-28c72ee7918f.png)

**Comment by ingorichter** [comment]
WTH! It seems the date format that's returned from the json feed has a different format. Let me check this quickly.

**Comment by larz0** [comment]
Thanks @ingorichter I think our WP blog has a life of its own.

**Comment by ingorichter** [comment]
Hey @larz0, I can't see the fancy date with Chrome. Which browser do you use?

**Comment by ingorichter** [comment]
Firefox is showing 'Invalid Date', Safari is showing this fancy date... :-(

**Comment by larz0** [comment]
I'm using Safari 7.0.1.

**Comment by ingorichter** [comment]
@larz0 I've fixed the issue. Would you mind having a second look? Thanks.

**Comment by larz0** [comment]
Yay it's fixed. Closing, thanks~
