### ISSUE TITLE
Feature Links Are Hard To See

### ISSUE THREAD

**Issue by adrocknaphobia** [adobe/brackets.io#5]
The color of the feature links are hard to see and looked washed out.

**Comment by Yomi0** [comment]
http://yomi0.github.io/brackets.io/index.html

https://github.com/yomi0/brackets.io/commit/1c9bd861dc962b44023399cb9d968876c0c20ecd

I changed the feature link colors to a darker blue.

**Comment by larz0** [comment]
@adrocknaphobia FBNC

**Comment by larz0** [comment]
Closing this.
