### ISSUE TITLE
Revoked certificate..?

### ISSUE THREAD

**Issue by bodhiBit** [adobe/brackets.io#65]
Firefox seems to believe your certificate for https://brackets-registry.aboutweb.com/ has been revoked..

![screenie](https://cloud.githubusercontent.com/assets/2022184/2811814/b3367d1c-ce32-11e3-9f6f-536b4332a669.png)

**Comment by marcelgerber** [comment]
@jadbox See http://stackoverflow.com/q/275878/3455922

**Comment by dangoor** [comment]
I've contacted the maintainer of the registry.

**Comment by dangoor** [comment]
Also, I'll note that Chrome still allows access to the registry site.

**Comment by jrowny** [comment]
New certificate is in place, but some browsers don't contain the chain (bundle). Waiting on a patch to support CA i.e. `ca: [fs.readFileSync('gd_bundle.crt')]`

**Comment by ficristo** [comment]
If you still see the issue, reopen
