### ISSUE TITLE
download page is broken

### ISSUE THREAD

**Issue by ghost** [adobe/brackets.io#68]
http://download.brackets.io/ doesn't work anymore. 

![sans titre](https://cloud.githubusercontent.com/assets/6444179/2976807/723953c8-dba4-11e3-911b-f603b8492fa8.png)

**Comment by njx** [comment]
D'oh, thanks for the note. I refiled this in our main bugbase as https://github.com/adobe/brackets/issues/7839. Closing.

**Comment by njx** [comment]
@MrVaykadji - this should be fixed now. (Also, you can just go to brackets.io directly - download.brackets.io has been deprecated.)

**Comment by ghost** [comment]
oh ok, then there are some wiki pages to review : https://github.com/adobe/brackets/wiki/Linux-Version for example.

I was actually trying to download the Linux version (but on my Windows computer, for liveUSB purposes), but I could manage to do that with the "release" page from github.

**Comment by njx** [comment]
Ah, thanks. The old URL is supposed to redirect to the new URL anyway, but we should fix those up.
